#ifndef UNTITLED6_CONSTANTS_H
#define UNTITLED6_CONSTANTS_H

#define MAX_LINE_LENGTH 82
#define MAX_KEY_LENGTH 50
#define MAX_VALUE_LEN 1000
#define MAX_FILE_NAME 256
#endif /*UNTITLED6_CONSTANTS_H */
